version: '3.2'
services:
  redis:
    image: redis
    ports: 
      - 6379:6379
  app:
    build: .
    ports:
      - "8000:8000"
  nginx:
    image: nginx
    volumes:
      - ./nginx/certs:/certs
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/options-ssl-nginx.conf:/app/conf/options-ssl-nginx.conf
    ports:
      - "80:80"
      - "443:443"
